import { Sora } from "next/font/google";
import "./globals.css";
import configurations from "@/_data/config";
import Navbar from "./components/navigation/Navbar";
import Footer from "./components/footer/Footer";
import Locked from "./components/Utils/Locked";

const tenor = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: configurations.metadata.title,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tenor.className}>
        <Navbar />
        {children}
        <Footer />
        {/* <Locked/> */}
      </body>
    </html>
  );
}
