import { Outfit } from "next/font/google";
import "./globals.css";
import configurations from "@/_data/config";
import Navbar from "./components/navigation/Navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: configurations.metadata.title,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
